version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: radio-together-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # root 계정 비밀번호
      MYSQL_DATABASE: radio_together        # 기본적으로 생성할 데이터베이스
      MYSQL_USER: admin                 # 사용자 계정
      MYSQL_PASSWORD: admin        # 사용자 계정 비밀번호
    ports:
      - "3306:3306"  # 호스트와 컨테이너 포트 매핑
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-rollback-on-timeout=ON
      --innodb_flush_log_at_trx_commit=2
      --innodb_file_per_table=ON
      --innodb_log_file_size=1G
      --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
      --innodb_buffer_pool_size=512M
      --innodb_ft_enable_stopword=OFF
      --max_connections=500
      --local_infile=1
      --explicit_defaults_for_timestamp=true
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - radio-together  # 네트워크 설정 추가

  redis:
    image: redis:7.2-alpine
    healthcheck:
      test: [ "CMD-SHELL","redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --databases 1
      --timeout 0
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    networks:
      - radio-together

volumes:
  mysql_data:

networks:
  radio-together:
    driver: bridge